from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd


def _resolve_manifest_path(
    manifest_path: Path,
    value: str | None,
) -> Path | None:
    if value is None:
        return None

    path = Path(value)

    if path.is_absolute():
        return path

    return (manifest_path.parent / path).resolve()


def generate_trace_report(
    manifest_path: Path,
    *,
    output_dir: Path | None = None,
) -> dict[str, Path]:
    manifest_path = manifest_path.resolve()

    manifest = json.loads(
        manifest_path.read_text(encoding="utf-8")
    )

    output = manifest.get("output", {})

    trace_path = _resolve_manifest_path(
        manifest_path,
        output.get("trace_path"),
    )
    exclusive_jobs_path = _resolve_manifest_path(
        manifest_path,
        output.get("exclusive_job_metrics_path"),
    )

    if trace_path is None or not trace_path.is_file():
        raise FileNotFoundError(
            f"Mapped trace does not exist: {trace_path}"
        )

    if (
        exclusive_jobs_path is None
        or not exclusive_jobs_path.is_file()
    ):
        raise FileNotFoundError(
            "Exclusive job metrics are required to generate "
            "the report"
        )

    if output_dir is None:
        output_dir = manifest_path.with_name(
            f"{manifest_path.stem}.report"
        )

    output_dir.mkdir(parents=True, exist_ok=True)

    trace = pd.read_csv(trace_path)
    exclusive_jobs = pd.read_csv(exclusive_jobs_path)

    required_trace_columns = {
        "mapped_workload_id",
        "mapped_num_gpus",
        "runtime_quantile_distance",
    }
    missing_trace = required_trace_columns - set(trace.columns)

    if missing_trace:
        raise ValueError(
            "Mapped trace is missing report columns: "
            f"{sorted(missing_trace)}"
        )

    required_exclusive_columns = {
        "exclusive_waiting_time_s",
        "mapped_solo_runtime_s",
    }
    missing_exclusive = (
        required_exclusive_columns
        - set(exclusive_jobs.columns)
    )

    if missing_exclusive:
        raise ValueError(
            "Exclusive metrics are missing report columns: "
            f"{sorted(missing_exclusive)}"
        )

    gpu_demand_path = output_dir / "gpu_demand.png"

    gpu_counts = (
        trace["mapped_num_gpus"]
        .value_counts()
        .sort_index()
    )

    figure, axis = plt.subplots(figsize=(6, 4))
    axis.bar(
        [str(value) for value in gpu_counts.index],
        gpu_counts.values,
    )
    axis.set_xlabel("GPUs requested")
    axis.set_ylabel("Mapped jobs")
    axis.set_title("Mapped GPU-demand distribution")
    figure.tight_layout()
    figure.savefig(gpu_demand_path, dpi=200)
    plt.close(figure)

    timeline_path = output_dir / "exclusive_job_times.png"

    waiting = pd.to_numeric(
        exclusive_jobs["exclusive_waiting_time_s"],
        errors="raise",
    )
    runtime = pd.to_numeric(
        exclusive_jobs["mapped_solo_runtime_s"],
        errors="raise",
    )

    job_indices = list(range(len(exclusive_jobs)))

    width = max(10.0, min(20.0, len(exclusive_jobs) / 4))
    figure, axis = plt.subplots(figsize=(width, 5))

    axis.bar(
        job_indices,
        waiting,
        label="Waiting time",
    )
    axis.bar(
        job_indices,
        runtime,
        bottom=waiting,
        label="Execution time",
    )

    axis.set_xlabel("Job index")
    axis.set_ylabel("Time (seconds)")
    axis.set_title(
        "Estimated exclusive waiting and execution times"
    )
    axis.legend()
    figure.tight_layout()
    figure.savefig(timeline_path, dpi=200)
    plt.close(figure)

    exclusive = manifest.get("exclusive_simulation") or {}
    mapping = manifest.get("mapping") or {}
    configuration = manifest.get("configuration") or {}
    selection = manifest.get("selection") or {}

    report_path = output_dir / "report.md"

    lines = [
        "# Generated Trace Report",
        "",
        "This report was generated by "
        "`trace-mapper report-generation`.",
        "",
        "## Configuration",
        "",
        "| Property | Value |",
        "|---|---:|",
        f"| Source cluster | "
        f"{str(configuration.get('source_cluster', 'unknown')).title()} |",
        f"| Random seed | "
        f"{configuration.get('seed', 'unknown')} |",
        f"| Mapped jobs | {len(trace):,} |",
        f"| Supported GPU counts | "
        f"{configuration.get('supported_gpu_counts')} |",
        f"| Arrival span | "
        f"{selection.get('selected_arrival_span_s', 0):,.2f} s |",
        "",
        "## Mapping Quality",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Unique workloads | "
        f"{mapping.get('unique_workload_count', 0):,} |",
        f"| Mean quantile distance | "
        f"{mapping.get('runtime_quantile_distance_mean', 0):.4f} |",
        f"| p95 quantile distance | "
        f"{mapping.get('runtime_quantile_distance_p95', 0):.4f} |",
        f"| Maximum quantile distance | "
        f"{mapping.get('runtime_quantile_distance_max', 0):.4f} |",
        "",
        "## Exclusive Execution Estimate",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Server GPUs | "
        f"{exclusive.get('server_gpu_count', 'N/A')} |",
        f"| Makespan | "
        f"{exclusive.get('makespan_s', 0):,.2f} s |",
        f"| Mean waiting time | "
        f"{exclusive.get('waiting_mean_s', 0):,.2f} s |",
        f"| p95 waiting time | "
        f"{exclusive.get('waiting_p95_s', 0):,.2f} s |",
        f"| p99 waiting time | "
        f"{exclusive.get('waiting_p99_s', 0):,.2f} s |",
        f"| Mean JCT | "
        f"{exclusive.get('jct_mean_s', 0):,.2f} s |",
        f"| p95 JCT | "
        f"{exclusive.get('jct_p95_s', 0):,.2f} s |",
        f"| p99 JCT | "
        f"{exclusive.get('jct_p99_s', 0):,.2f} s |",
        "",
        "## GPU Demand",
        "",
        "![Mapped GPU-demand distribution](gpu_demand.png)",
        "",
        "## Estimated Job Times",
        "",
        "![Estimated exclusive job times]"
        "(exclusive_job_times.png)",
        "",
        "The enriched mapped trace, execution-only trace, "
        "manifest, and exclusive job metrics remain the "
        "authoritative machine-readable artifacts.",
        "",
    ]

    report_path.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    return {
        "report_path": report_path,
        "gpu_demand_path": gpu_demand_path,
        "timeline_path": timeline_path,
    }
