from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd


def _resolve_manifest_path(
    manifest_path: Path,
    value: str | None,
) -> Path | None:
    if value is None:
        return None

    path = Path(value)

    if path.is_absolute():
        return path

    return (manifest_path.parent / path).resolve()


def generate_trace_report(
    manifest_path: Path,
    *,
    output_dir: Path | None = None,
) -> dict[str, Path]:
    manifest_path = manifest_path.resolve()

    manifest = json.loads(
        manifest_path.read_text(encoding="utf-8")
    )

    output = manifest.get("output", {})

    trace_path = _resolve_manifest_path(
        manifest_path,
        output.get("trace_path"),
    )
    exclusive_jobs_path = _resolve_manifest_path(
        manifest_path,
        output.get("exclusive_job_metrics_path"),
    )

    if trace_path is None or not trace_path.is_file():
        raise FileNotFoundError(
            f"Mapped trace does not exist: {trace_path}"
        )

    if (
        exclusive_jobs_path is None
        or not exclusive_jobs_path.is_file()
    ):
        raise FileNotFoundError(
            "Exclusive job metrics are required to generate "
            "the report"
        )

    if output_dir is None:
        output_dir = manifest_path.with_name(
            f"{manifest_path.stem}.report"
        )

    output_dir.mkdir(parents=True, exist_ok=True)

    trace = pd.read_csv(trace_path)
    exclusive_jobs = pd.read_csv(exclusive_jobs_path)

    required_trace_columns = {
        "mapped_workload_id",
        "mapped_num_gpus",
        "runtime_quantile_distance",
    }
    missing_trace = required_trace_columns - set(trace.columns)

    if missing_trace:
        raise ValueError(
            "Mapped trace is missing report columns: "
            f"{sorted(missing_trace)}"
        )

    required_exclusive_columns = {
        "exclusive_waiting_time_s",
        "mapped_solo_runtime_s",
    }
    missing_exclusive = (
        required_exclusive_columns
        - set(exclusive_jobs.columns)
    )

    if missing_exclusive:
        raise ValueError(
            "Exclusive metrics are missing report columns: "
            f"{sorted(missing_exclusive)}"
        )

    gpu_demand_path = output_dir / "gpu_demand.png"

    gpu_counts = (
        trace["mapped_num_gpus"]
        .value_counts()
        .sort_index()
    )

    figure, axis = plt.subplots(figsize=(6, 4))
    axis.bar(
        [str(value) for value in gpu_counts.index],
        gpu_counts.values,
    )
    axis.set_xlabel("GPUs requested")
    axis.set_ylabel("Mapped jobs")
    axis.set_title("Mapped GPU-demand distribution")
    figure.tight_layout()
    figure.savefig(gpu_demand_path, dpi=200)
    plt.close(figure)

    timeline_path = output_dir / "exclusive_job_times.png"

    waiting = pd.to_numeric(
        exclusive_jobs["exclusive_waiting_time_s"],
        errors="raise",
    )
    runtime = pd.to_numeric(
        exclusive_jobs["mapped_solo_runtime_s"],
        errors="raise",
    )

    job_indices = list(range(len(exclusive_jobs)))

    width = max(10.0, min(20.0, len(exclusive_jobs) / 4))
    figure, axis = plt.subplots(figsize=(width, 5))

    axis.bar(
        job_indices,
        waiting,
        label="Waiting time",
    )
    axis.bar(
        job_indices,
        runtime,
        bottom=waiting,
        label="Execution time",
    )

    axis.set_xlabel("Job index")
    axis.set_ylabel("Time (seconds)")
    axis.set_title(
        "Estimated exclusive waiting and execution times"
    )
    axis.legend()
    figure.tight_layout()
    figure.savefig(timeline_path, dpi=200)
    plt.close(figure)

    exclusive = manifest.get("exclusive_simulation") or {}
    mapping = manifest.get("mapping") or {}
    configuration = manifest.get("configuration") or {}
    selection = manifest.get("selection") or {}

    report_path = output_dir / "report.md"

    lines = [
        "# Generated Trace Report",
        "",
        "This report was generated by "
        "`trace-mapper report-generation`.",
        "",
        "## Configuration",
        "",
        "| Property | Value |",
        "|---|---:|",
        f"| Source cluster | "
        f"{str(configuration.get('source_cluster', 'unknown')).title()} |",
        f"| Random seed | "
        f"{configuration.get('seed', 'unknown')} |",
        f"| Mapped jobs | {len(trace):,} |",
        f"| Supported GPU counts | "
        f"{configuration.get('supported_gpu_counts')} |",
        f"| Arrival span | "
        f"{selection.get('selected_arrival_span_s', 0):,.2f} s |",
        "",
        "## Mapping Quality",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Unique workloads | "
        f"{mapping.get('unique_workload_count', 0):,} |",
        f"| Mean quantile distance | "
        f"{mapping.get('runtime_quantile_distance_mean', 0):.4f} |",
        f"| p95 quantile distance | "
        f"{mapping.get('runtime_quantile_distance_p95', 0):.4f} |",
        f"| Maximum quantile distance | "
        f"{mapping.get('runtime_quantile_distance_max', 0):.4f} |",
        "",
        "## Exclusive Execution Estimate",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Server GPUs | "
        f"{exclusive.get('server_gpu_count', 'N/A')} |",
        f"| Makespan | "
        f"{exclusive.get('makespan_s', 0):,.2f} s |",
        f"| Mean waiting time | "
        f"{exclusive.get('waiting_mean_s', 0):,.2f} s |",
        f"| p95 waiting time | "
        f"{exclusive.get('waiting_p95_s', 0):,.2f} s |",
        f"| p99 waiting time | "
        f"{exclusive.get('waiting_p99_s', 0):,.2f} s |",
        f"| Mean JCT | "
        f"{exclusive.get('jct_mean_s', 0):,.2f} s |",
        f"| p95 JCT | "
        f"{exclusive.get('jct_p95_s', 0):,.2f} s |",
        f"| p99 JCT | "
        f"{exclusive.get('jct_p99_s', 0):,.2f} s |",
        "",
        "## GPU Demand",
        "",
        "![Mapped GPU-demand distribution](gpu_demand.png)",
        "",
        "## Estimated Job Times",
        "",
        "![Estimated exclusive job times]"
        "(exclusive_job_times.png)",
        "",
        "The enriched mapped trace, execution-only trace, "
        "manifest, and exclusive job metrics remain the "
        "authoritative machine-readable artifacts.",
        "",
    ]

    report_path.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    return {
        "report_path": report_path,
        "gpu_demand_path": gpu_demand_path,
        "timeline_path": timeline_path,
    }


def generate_trace_suite_report(
    manifest_paths: list[Path],
    *,
    output_dir: Path,
) -> dict[str, Path]:
    if not manifest_paths:
        raise ValueError(
            "At least one manifest is required"
        )

    output_dir.mkdir(parents=True, exist_ok=True)

    rows = []

    for manifest_path in manifest_paths:
        manifest_path = manifest_path.resolve()

        manifest = json.loads(
            manifest_path.read_text(encoding="utf-8")
        )

        configuration = manifest.get(
            "configuration",
            {},
        )
        selection = manifest.get("selection", {})
        mapping = manifest.get("mapping", {})
        exclusive = manifest.get(
            "exclusive_simulation"
        )
        output = manifest.get("output", {})

        if not isinstance(exclusive, dict):
            raise ValueError(
                f"{manifest_path} has no exclusive simulation"
            )

        trace_path = _resolve_manifest_path(
            manifest_path,
            output.get("trace_path"),
        )

        if trace_path is None or not trace_path.is_file():
            raise FileNotFoundError(
                f"Mapped trace does not exist: {trace_path}"
            )

        trace = pd.read_csv(trace_path)

        required_columns = {
            "mapped_num_gpus",
            "mapped_workload_id",
        }
        missing = required_columns - set(trace.columns)

        if missing:
            raise ValueError(
                f"{trace_path} is missing columns: "
                f"{sorted(missing)}"
            )

        one_gpu_jobs = int(
            (trace["mapped_num_gpus"] == 1).sum()
        )
        two_gpu_jobs = int(
            (trace["mapped_num_gpus"] == 2).sum()
        )

        rows.append(
            {
                "trace": str(
                    configuration.get(
                        "source_cluster",
                        manifest_path.stem,
                    )
                ).title(),
                "job_count": int(len(trace)),
                "one_gpu_jobs": one_gpu_jobs,
                "two_gpu_jobs": two_gpu_jobs,
                "unique_workloads": int(
                    trace["mapped_workload_id"].nunique()
                ),
                "arrival_span_s": float(
                    selection.get(
                        "selected_arrival_span_s",
                        0.0,
                    )
                ),
                "quantile_distance_mean": float(
                    mapping.get(
                        "runtime_quantile_distance_mean",
                        0.0,
                    )
                ),
                "quantile_distance_p95": float(
                    mapping.get(
                        "runtime_quantile_distance_p95",
                        0.0,
                    )
                ),
                "makespan_s": float(
                    exclusive["makespan_s"]
                ),
                "waiting_mean_s": float(
                    exclusive["waiting_mean_s"]
                ),
                "waiting_p95_s": float(
                    exclusive["waiting_p95_s"]
                ),
                "waiting_p99_s": float(
                    exclusive["waiting_p99_s"]
                ),
                "jct_mean_s": float(
                    exclusive["jct_mean_s"]
                ),
                "jct_p95_s": float(
                    exclusive["jct_p95_s"]
                ),
                "jct_p99_s": float(
                    exclusive["jct_p99_s"]
                ),
            }
        )

    comparison = pd.DataFrame(rows).sort_values(
        "trace",
        kind="mergesort",
    ).reset_index(drop=True)

    comparison_csv_path = (
        output_dir / "generated_trace_comparison.csv"
    )
    comparison.to_csv(
        comparison_csv_path,
        index=False,
    )

    makespan_path = output_dir / "exclusive_makespan.png"

    figure, axis = plt.subplots(figsize=(7, 4))
    axis.bar(
        comparison["trace"],
        comparison["makespan_s"] / 3600.0,
    )
    axis.set_xlabel("Production trace")
    axis.set_ylabel("Estimated makespan (hours)")
    axis.set_title(
        "Estimated exclusive execution makespan"
    )
    figure.tight_layout()
    figure.savefig(makespan_path, dpi=200)
    plt.close(figure)

    waiting_path = output_dir / "waiting_time_p95.png"

    figure, axis = plt.subplots(figsize=(7, 4))
    axis.bar(
        comparison["trace"],
        comparison["waiting_p95_s"] / 60.0,
    )
    axis.set_xlabel("Production trace")
    axis.set_ylabel("p95 waiting time (minutes)")
    axis.set_title(
        "Estimated exclusive p95 waiting time"
    )
    figure.tight_layout()
    figure.savefig(waiting_path, dpi=200)
    plt.close(figure)

    gpu_mix_path = output_dir / "mapped_gpu_mix.png"

    figure, axis = plt.subplots(figsize=(7, 4))
    axis.bar(
        comparison["trace"],
        comparison["one_gpu_jobs"],
        label="1-GPU jobs",
    )
    axis.bar(
        comparison["trace"],
        comparison["two_gpu_jobs"],
        bottom=comparison["one_gpu_jobs"],
        label="2-GPU jobs",
    )
    axis.set_xlabel("Production trace")
    axis.set_ylabel("Mapped jobs")
    axis.set_title("Mapped GPU-demand composition")
    axis.legend()
    figure.tight_layout()
    figure.savefig(gpu_mix_path, dpi=200)
    plt.close(figure)

    report_path = output_dir / "generated_trace_comparison.md"

    lines = [
        "# Generated Trace Comparison",
        "",
        "This report is generated by "
        "`trace-mapper report-generation-suite` from the "
        "mapped-trace manifests.",
        "",
        "| Trace | Jobs | 1-GPU | 2-GPU | Unique workloads | "
        "Arrival span | Exclusive makespan | Waiting p95 | "
        "JCT p95 | Mapping-distance p95 |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]

    for row in comparison.to_dict(orient="records"):
        lines.append(
            f"| {row['trace']} | "
            f"{row['job_count']} | "
            f"{row['one_gpu_jobs']} | "
            f"{row['two_gpu_jobs']} | "
            f"{row['unique_workloads']} | "
            f"{row['arrival_span_s'] / 3600:.2f} h | "
            f"{row['makespan_s'] / 3600:.2f} h | "
            f"{row['waiting_p95_s'] / 60:.2f} min | "
            f"{row['jct_p95_s'] / 60:.2f} min | "
            f"{row['quantile_distance_p95']:.4f} |"
        )

    lines.extend(
        [
            "",
            "## Exclusive Makespan",
            "",
            "![Estimated exclusive makespan]"
            "(exclusive_makespan.png)",
            "",
            "## Waiting Time",
            "",
            "![Estimated p95 waiting time]"
            "(waiting_time_p95.png)",
            "",
            "## GPU-Demand Composition",
            "",
            "![Mapped GPU-demand composition]"
            "(mapped_gpu_mix.png)",
            "",
            "The estimates assume arrival-order execution with "
            "exclusive GPU allocation on the configured server. "
            "They are intended for experiment planning rather than "
            "as measured scheduler results.",
            "",
        ]
    )

    report_path.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    return {
        "report_path": report_path,
        "comparison_csv_path": comparison_csv_path,
        "makespan_path": makespan_path,
        "waiting_path": waiting_path,
        "gpu_mix_path": gpu_mix_path,
    }